name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Running tests
        run: |
          sudo apt-get update
          sudo apt-get install nodejs npm -y
          npm install
          CI=true npm test

      - name: Executing Next Step
        run: echo "Tests are successful"
        
